previewsEnabled: true
services:
  - type: web
    name: sample-ruby-app
    env: ruby
    initialDeployHook: ./render-initialDeployHook.sh
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh
